matrix:
  include:
    - os: osx
      osx_image: xcode10.2

language:
    c

before_install:
    - brew update
    - brew install llvm@8
    - brew outdated llvm@8 || brew upgrade llvm@8

install:
    - mkdir build
    - cd build
    - CC=gcc-8 CXX=g++-8 cmake .. -DCMAKE_PREFIX_PATH=/usr/local/opt/llvm -DCMAKE_INSTALL_PREFIX=$(pwd)/installdir
    - make -j3 install
    - installdir/bin/zig --help
    - installdir/bin/zig run ../panic_test.zig

notifications:
    email: false
