matrix:
  include:
    - os: osx
      osx_image: xcode10.2

language:
    c

# compiler:
#     - gcc

before_install:
    - brew update
    - brew install gcc@8 || brew link --overwrite gcc
    - brew install cmake llvm@8
    - brew outdated llvm@8 || brew upgrade llvm@8

install:
    - mkdir build
    - cd build
    - CC=gcc-8 CXX=g++-8 cmake .. -DCMAKE_PREFIX_PATH=$(pwd)/../llvm+clang-8.0.0-macos-x86_64-gcc8-release-static -DCMAKE_INSTALL_PREFIX=$(pwd)/installdir
    - make -j3 install
    - installdir/bin/zig --help

notifications:
    email: false
