matrix:
  include:
    - os: osx
      osx_image: xcode10.2

language:
    c

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

before_install:
    - brew update
    - brew install llvm@8
    - brew outdated llvm@8 || brew upgrade llvm@8
    - brew install gcc@8 || brew link --overwrite gcc
    - export CC=gcc-8
    - export CXX=g++-8

install:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/local/opt/llvm -DCMAKE_INSTALL_PREFIX=$(pwd)/installdir
    - make -j2 install
    - installdir/bin/zig --help
    - installdir/bin/zig build --build-file ../build.zig test

notifications:
    email: false
